apiVersion: v1
kind: Service
metadata:
  name: example-server-app
  namespace: apps
spec:
  # This selects the pods that were created by the example-server-app deployment.
  selector:
    app: example-server-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
